#!/bin/sh

export GTK_THEME=Adwaita:dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
export QT_STYLE_OVERRIDE=adwaita-dark
export DESKTOP_SESSION=plasma
export XDG_CURRENT_DESKTOP=KDE
